version: '3.8'

services:
  project_capstone:
    image: postgres:latest
    environment:
      POSTGRES_USER: dewa_capstone
      POSTGRES_PASSWORD: dewa_capstone
      POSTGRES_DB: project_caps3
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: